[package]
name = "join_to_string"
version = "0.1.0"

authors = ["Aleksey Kladov <aleksey.kladov@gmail.com>"]
repository = "https://github.com/matklad/typed_key"
license = "MIT OR Apache-2.0"

categories = [ "rust-patterns" ]
description = """
Join a list of items to string/buffer.
"""
